module:
  hugoVersion:
    min: "0.64.0"
  mounts:
  - source: partials
    target: layouts/partials/tnd-snipcart
  - source: console
    target: layouts/partials/tnd-snipcart
  imports: 
    - path: github.com/theNewDynamic/hugo-module-tnd-tags